name: Upload to Azure Storage

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Azure CLI
      uses: azure/setup-azure-cli@v2
      with:
        version: latest

    - name: Authenticate with Azure
      run: az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}

    # - name: Upload file to Azure Storage
    #   run: |
    #     az storage blob upload --account-name yourstorageaccountname --account-key yourstorageaccountkey --container-name yourcontainername --file example.txt --name example.txt
