name: Upload YAML Files to Azure Storage

on:
  workflow_dispatch:
  
jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Login to Azure
      run: az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}

    - name: Upload YAML files to Azure Storage
      run: |
        az storage blob upload-batch --source 'sample_react/**/*.txt' --destination ${{ secrets.AZURE_STORAGE_CONTAINER_NAME }} --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}
